### ISSUE TITLE
Immutable.js dependency version mismatch with Draft.js

### ISSUE THREAD

**Issue by thibaudcolas** [icelab/draft-js-single-line-plugin#4]
👋 I'm considering using this plugin for my editor, but looking at its dependencies I see it uses Immutable.js `^3.8.1`:

https://github.com/icelab/draft-js-single-line-plugin/blob/576afbb85858901c5a550a6a5651dbad95b8dc5c/package.json#L51

This is incompatible with Draft.js itself, which requires `~3.7.4` (https://github.com/facebook/draft-js/blob/37dadd35d76768ae8109297afad6d498cfa3bd60/package.json#L37). The consequence of this mismatch is that now my JS bundle contains two copies of Immutable, which is quite a big dependency.

From what I can see in the plugin's code, Immutable.js is only used to interact with Draft.js via `List` and `Map`. This should work the same in v3.7.4 – would it be possible to change the dependency requirement to match that of Draft.js?

**Comment by makenosound** [comment]
@thibaudcolas Ah, good catch. Have release v2.0.2 that changes range to match draft-js.

**Comment by thibaudcolas** [comment]
👌 thank you!

**Comment by TrySound** [comment]
@makenosound Looks like this was not fixed.
https://github.com/icelab/draft-js-single-line-plugin/blob/master/package.json#L56
